baseURL = "https://rdnz.dev/"
theme = "hugo-bearcub"

title = "Guilherme Raduenz"
author = "Guilherme Raduenz"
copyright = "Copyright © 2024, Guilherme Raduenz"
languageCode = "en-US"

enableRobotsTXT = true

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[permalinks]
  [permalinks.page]
    blog = "/:slug"
    tags = "/blog/:slug"
    labs = "/labs/:slug"
  [permalinks.section]
    blog = '/'

[params]
  madeWith = "Made with [Hugo](https://gohugo.io/) and [Bear Cub](https://github.com/clente/hugo-bearcub)"
  description = "Guilherme Raduenz's website"
  title = "Guilherme Raduenz"
  dateFormat = "2006-01-02"
  themeStyle = "original"

  [params.author]
    name = "Guilherme Raduenz"
    email = "gui@rdnz.dev"